In [7]:
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

# Network size
N_input = 4
N_hidden = 3
N_output = 2

np.random.seed(42)
# Make some fake data
X = np.random.randn(4)

print("X")
print(X)
print("")
weights_in_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
weights_hidden_out = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))

print("weights_in_hidden")
print(weights_in_hidden)


X
[ 0.49671415 -0.1382643   0.64768854  1.52302986]

weights_in_hidden
[[-0.02341534 -0.0234137   0.15792128]
 [ 0.07674347 -0.04694744  0.054256  ]
 [-0.04634177 -0.04657298  0.02419623]
 [-0.19132802 -0.17249178 -0.05622875]]


In [4]:
hidden_layer_in = np.dot(X,weights_in_hidden)
print(hidden_layer_in)

[-0.34365494 -0.29801368  0.00097362]


In [9]:
hidden_layer_out = sigmoid(hidden_layer_in)



hidden_layer_out
[ 0.41492192  0.42604313  0.5002434 ]



In [10]:
print('Hidden-layer Output:')
print(hidden_layer_out)
print("")

Hidden-layer Output:
[ 0.41492192  0.42604313  0.5002434 ]



In [12]:
print("hidden_layer_out")
print(hidden_layer_out)

output_layer_in = np.dot(hidden_layer_out, weights_hidden_out)



hidden_layer_out
[ 0.41492192  0.42604313  0.5002434 ]


In [13]:
output_layer_out = sigmoid(output_layer_in)

In [14]:
print('Output-layer Output:')
print(output_layer_out)

Output-layer Output:
[ 0.49815196  0.48539772]
